---
title: "WA_Schl_Data"
author: "Lamar Foster"
date: "5/19/2020"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(readr)
library(janitor)
library(ggthemes)
library(knitr)
```

```{r}
download.file(url = "https://data.wa.gov/api/views/u4gd-6wxx/rows.csv?accessType=DOWNLOAD", destfile = "WA_Data.csv")
```

```{r, include = F}
WA_Data <-  read_csv("WA_Data.csv")
glimpse(WA_Data)
names(WA_Data)
```

```{r}
WA_Data <- clean_names(WA_Data)
WA_Data <- WA_Data %>% 
  rename(ell = english_language_learners) ###Rename variable name
```

```{r}
names(WA_Data)
```

```{r}
#Max School District Enrollment for Certain ESDs
WA_Data %>% 
  select(c("esd_name", "school_name", "district_name", "school_year", "grade_level", "all_students")) %>% 
  group_by(esd_name) %>% 
  filter(esd_name %in%  c("Olympic Educational Service District 114", "Puget Sound Educational Service District 121", "Educational Service District 123", "North Central Educational Service District 171", "Northwest Educational Service District 189"), school_name == "District Total", grade_level == "AllGrades", all_students == max(all_students))
```

```{r}
#Slimming Dataframe and getting low-income percentage
WA_Data2 <- WA_Data %>% 
  select(county, esd_name, district_name, school_name, all_students, ell, low_income, grade_level) %>%
  filter(grade_level == "AllGrades", !is.na(esd_name), school_name == 'District Total', !esd_name %in%  c("Spokane Public Schools Charter Authorizer", "Washington State Charter School Commission"))%>% 
  mutate(low_income_percent = (low_income/all_students)*100) %>% 
  arrange(desc(low_income_percent))
```

```{r}
##Get unique ESD Names
unique(WA_Data2$esd_name)
```

```{r}
#Stratified Sample 
SS <- WA_Data2 %>% 
  group_by(esd_name) %>% 
  filter(low_income_percent > 50) %>% 
  sample_n(2, replace = T) %>% 
  arrange(esd_name)
```

```{r}
#Simple Visualization 

ggplot(SS, aes(reorder(district_name, +low_income_percent), low_income_percent, fill = esd_name)) + geom_col() + coord_flip() + labs(y= "Percentage of Low-Income Students", x= "School District", fill = "ESD Name") +     theme_calc() 

```

```{r}
#Table of Sampled School Districts

kable(SS[1:18,c(2,3,5,9)])
```


